name: C++ Busqueda_Binaria Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Git
      run: |
        git config --global user.name "Elisacv8"
        git config --global user.email "vasquezelisa597@gmail.com"

    - name: Install Dependencies
      run: sudo apt-get install -y g++

    - name: Compile C++ Code
      run: g++ -o Busqueda_Binaria Busqueda_Binaria.cpp

    - name: Run C++ Program
      run: ./Busqueda_Binaria